AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable

Layout/LineLength:
  Max: 120
  
Metrics/BlockLength:
  Exclude:
    - spec/**/*
  IgnoredMethods:
    - context
    - describe
    - shared_examples

